# Generated by Django 5.1.7 on 2025-03-26 10:00

import django.db.models.deletion
import rest.Validators.custom_validator
import rest.customfield
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('d', 'Developer'), ('qa', 'Quality Assurance'), ('m', 'Manager'), ('a', 'System Architect'), ('n', 'Networks Engineer')], max_length=2, verbose_name='Professional Designation')),
                ('profile_picture', models.ImageField(blank=True, help_text='Max img size 5mb', null=True, upload_to='profile_pics/', validators=[rest.Validators.custom_validator.validate_image])),
                ('contact_number', rest.customfield.CustomPhoneNumberField(blank=True, max_length=15)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('team_members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='documents/')),
                ('version', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rest.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('o', 'Open'), ('r', 'Review'), ('w', 'Working'), ('ar', 'Awaiting Release'), ('wq', 'Waiting QA')], max_length=2, verbose_name='Task Status')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Comment')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.task')),
            ],
        ),
    ]
