# Generated by Django 5.1.7 on 2025-03-28 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(related_name='team', to=settings.AUTH_USER_MODEL),
        ),
    ]
